## templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: evemapper-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  EVE_CLIENT_SECRET: {{ .Values.secrets.EVE_CLIENT_SECRET | b64enc }}