apiVersion: v1
kind: Service
metadata:
  name: evemapper-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    component: evemapper-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080